const $=s=>document.querySelector(s);
const element=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;};
const number=n=>Number(n||0).toLocaleString('zh-CN');
const short=n=>n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'k':number(n);
const time=value=>value?new Date(value).toLocaleTimeString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'}):'—';
const duration=ms=>{const s=Math.max(0,Math.floor((ms||0)/1000));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':');};
const ago=t=>{const s=Math.max(0,Math.floor((Date.now()-Date.parse(t))/1000));return s<60?s+' 秒前':s<3600?Math.floor(s/60)+' 分钟前':Math.floor(s/3600)+' 小时前';};
const labels={paused:'已暂停',running:'运行中',idle:'无活动执行',interrupted:'执行中断',unknown:'状态未知',waiting:'等待调度',recorded:'已有记录',conditional:'条件启动',queued:'等待执行',failed:'执行失败',budget_exhausted:'预算耗尽',ready_for_human_review:'待人工审查',completed_with_gaps:'完成，仍有缺口',reviewing:'审稿',revising:'修订',drafting:'写作',collecting:'证据收集',verifying:'复核',success:'已完成',saved:'已保存',supported:'支持',partially_supported:'部分支持',contradicted:'相矛盾',insufficient_evidence:'证据不足',not_accessible:'无法访问',pending:'待核查',pi_live:'真实模型',fixture:'测试夹具',host:'宿主',human_revision:'人工修改',agent_live:'Agent 生成',imported_session:'导入会话'};
const eventLabels={model_request_reserved:'发起模型请求',model_usage:'模型用量返回',tool_executed:'读取证据',pi_session_started:'Pi 会话开始',stage_started:'阶段开始',stage_success:'阶段完成',stage_failure:'阶段失败',workflow_finished:'工作流结束',citation_check_completed:'引文核查完成',citation_audit_batch_completed:'引文批次完成',citation_verification_stopped:'引文查证停止',revalidation_stage_started:'重新核验阶段开始',model_envelope_preserved:'模型结果已保存',semantic_output_rejected:'输出校验未通过',failed_model_usage:'失败请求用量',unknown_usage_reservation_retained:'保留未知用量预留',successful_stage_reused:'复用成功检查点',budget_extended:'预算已调整',zotero_sync_completed:'Zotero 同步完成',literature_batch_read:'文献阅读批次完成',citation_locator_deterministically_resolved:'引文定位已解析',pi_event:'Pi 事件'};
const roleDescriptions={evidence:'证据构建 / 来源边界',author:'科学写作 / 审稿回应',reviewer:'独立审稿 / 问题定位',editor:'编辑裁决 / 分歧整合',red_team:'反证 / 替代解释',citation_verifier:'逐处引证 / 原文核查',prose_adjudicator:'独立语言裁决 / 科学措辞',translator:'中文翻译 / 段落对齐'};
const roleInitials={evidence:'EA',author:'SA',reviewer:'CR',editor:'ME',red_team:'RT',citation_verifier:'CV',prose_adjudicator:'PA',translator:'ST'};
let project='',generation=0,stream=null,snapshot=null,events=[],cursor,view='overview',frozen=null,citations=null,output=null,outputRef='',eventBusy=false,citationBusy=false,lastCitationsKey='',stageKey='',outputsKey='';
const agentNodes=new Map(),tweens=new Map();
function animateNumber(selector,value){const target=$(selector),old=tweens.get(selector);if(old?.goal===value)return;if(old)cancelAnimationFrame(old.frame);const from=old?.current??value,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,start=performance.now();const state={goal:value,current:from,frame:0};tweens.set(selector,state);function tick(now){const p=reduce?1:Math.min(1,(now-start)/650),ease=1-Math.pow(1-p,3);state.current=from+(value-from)*ease;target.textContent=number(Math.round(state.current));if(p<1)state.frame=requestAnimationFrame(tick);}state.frame=requestAnimationFrame(tick);}
function message(text=''){$('#message').hidden=!text;$('#message').textContent=text;}
function connection(state,text){$('#connection-dot').className='dot '+state;$('#connection-text').textContent=text;document.body.classList.toggle('disconnected',state==='offline');}
function badge(text,status){return element('span',text,'badge '+status);}
async function api(route,params={}){const url=new URL(route,RF_SERVER);if(project)url.searchParams.set('project',project);for(const[k,v]of Object.entries(params))url.searchParams.set(k,v);const response=await cloudFetch(url);let result;try{result=await response.json();}catch{throw Error('服务没有返回可读数据');}if(!response.ok)throw Error(result.error||'读取失败');return result;}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function eventName(e){return e.type==='pi_event'?'Pi · '+(e.details?.type||'event'):eventLabels[e.type]||e.type;}
function detail(title,content){$('#detail-title').textContent=title;$('#detail-body').replaceChildren(content);if(!$('#detail').open)$('#detail').showModal();}
function jsonView(data){const e=element('pre');e.textContent=JSON.stringify(data,null,2);return e;}
function errorMessage(error){message(error.message||String(error));}

async function loadProjects(){const tag=generation;const list=await api('/reviewforge/api/monitor-projects');if(tag!==generation)return;const wanted=new URLSearchParams(location.search).get('project');const selected=list.some(p=>p.id===project)?project:list.some(p=>p.id===wanted)?wanted:list[0]?.id||'';$('#project').replaceChildren(...list.map(p=>{const o=element('option',(p.runtime==='running'?'● ':'')+publicProjectLabel(p.id)+(p.fixture?' · 测试夹具':''));o.value=p.id;return o;}));$('#project').value=selected;$('#empty').hidden=!!selected;if(selected!==project)selectProject(selected);if(!selected){connection('offline','没有项目');document.querySelectorAll('.view,.project-banner').forEach(e=>e.hidden=true);}}
function selectProject(id){generation++;project=id;stream?.close();snapshot=null;events=[];cursor=undefined;citations=null;output=null;outputRef='';frozen=null;eventBusy=false;citationBusy=false;lastCitationsKey='';stageKey='';outputsKey='';agentNodes.clear();$('#agents').replaceChildren();$('#stages').replaceChildren();$('#outputs').replaceChildren();$('#recent-events').replaceChildren();$('#citation-rows').replaceChildren();$('#event-rows').replaceChildren();$('#export-output').disabled=true;$('#output-title').textContent='产物预览';$('#output-preview').replaceChildren(element('p','选择一份稿件或报告。','muted'));$('#freeze-events').textContent='冻结列表';message();if(!id)return;const url=new URL(location.href);url.searchParams.set('project',id);history.replaceState(null,'',url);$('#feedback-link').href='/feedback?project='+encodeURIComponent(id);connection('','正在连接');const tag=generation;stream=new PhoneStream('/reviewforge/api/monitor-stream?project='+encodeURIComponent(id));stream.addEventListener('snapshot',e=>{if(tag!==generation)return;try{snapshot=JSON.parse(e.data);connection('live','实时连接 · 腾讯云同步');message();renderSnapshot();void fetchEvents();if(view==='citations')void fetchCitations();}catch(error){errorMessage(error);}});stream.addEventListener('monitor_error',e=>{if(tag!==generation)return;connection('offline','数据读取失败');errorMessage(JSON.parse(e.data));});stream.onerror=()=>{if(tag===generation)connection('offline','连接中断 · 正在重连');};}
function setView(next){view=next;const names={overview:'运行总览',events:'实时事件',citations:'引文查证',outputs:'稿件与报告'};document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!=='view-'+next);document.querySelectorAll('button.nav').forEach(e=>{e.classList.toggle('active',e.dataset.view===next);e.setAttribute('aria-current',e.dataset.view===next?'page':'false');});$('#heading').textContent=names[next];$('#view-label').textContent=names[next];if(next==='events')renderEvents();if(next==='citations')void fetchCitations(true);}
function renderSnapshot(){document.querySelector(".project-banner").hidden=false;setView(view);const s=snapshot;if(!s)return;$("#runtime-model").textContent="Pi Agent · "+s.model;document.body.classList.toggle('is-running',s.runtime.state==='running');$('#runtime').textContent=labels[s.runtime.state]||s.runtime.state;$('#runtime').className='badge '+s.runtime.state;$('#process').textContent=(s.runtime.pid?'PID '+s.runtime.pid+' · ':'')+'台账：'+(labels[s.project.status]||s.project.status);$('#project-title').textContent=s.project.title;$('#project-question').textContent=s.project.question;$('#observed').textContent='读取于 '+time(s.observed_at);$('#alerts').replaceChildren(...s.alerts.map(a=>element('div',a.text,'alert '+a.kind)));animateNumber('#requests',s.ledger.requests);$('#request-limit').textContent=s.limits.requests===null?'/ 无上限':'/ '+number(s.limits.requests);$('#request-note').textContent='当前 '+s.active_requests.length+' 个请求 · 服务端重试次数未知';animateNumber('#tokens',s.measured_tokens);const tokenRatio=s.limits.tokens?s.budget_tokens/s.limits.tokens:0;$('#token-meter').style.width=Math.min(100,tokenRatio*100)+'%';$('#token-meter').classList.toggle('danger',tokenRatio>=.9);$('#token-note').textContent='预算 '+short(s.limits.tokens)+' · 预留 '+short(s.ledger.reserved_tokens)+' · 费用未知';animateNumber('#checked',s.citations.checked);$('#citation-total').textContent='/ '+number(s.citations.total);$('#citation-meter').style.width=(s.citations.total?s.citations.checked/s.citations.total*100:0)+'%';$('#citation-note').textContent='待核查 '+s.citations.pending+' · 结果按稿件版本匹配';$('#elapsed').textContent=duration(s.elapsed_ms);$('#elapsed-note').textContent=s.limits.seconds===null?'累计执行时间 · 无宿主时间上限':'累计执行时间 · 上限 '+duration(s.limits.seconds*1000);$('#source-total').textContent=number(s.sources.total);$('#source-access').textContent=s.sources.full_text+' / '+s.sources.abstract;$('#draft-version').textContent=s.draft?.version||'尚无稿件';$('#body-words').textContent=s.draft?number(s.draft.body_words)+(s.draft.minimum?' / '+number(s.draft.minimum)+'–'+number(s.draft.maximum):''): '—';$('#unknown-usage').textContent=number(s.ledger.unknown_usage_requests);renderTelemetry(s.telemetry);renderInstruments(s);renderProgress(s.progress);renderAgents(s.agents);renderFlow(s.agents);renderStages(s.stages);renderOutputs(s.artifacts);renderActivity();}
function renderActivity(){if(!snapshot)return;const e=snapshot.last_event;$('#last-activity').textContent=e?ago(e.timestamp)+' · '+eventName(e):'暂无事件';if(snapshot.runtime.state==='running')$('#elapsed').textContent=duration(snapshot.elapsed_ms+Date.now()-Date.parse(snapshot.observed_at));for(const a of snapshot.agents){const ui=agentNodes.get(a.role);if(ui&&a.status==='running'){const oldest=a.active_requests.map(r=>Date.parse(r.at)).reduce((x,y)=>Math.min(x,y),Date.now());ui.stage.textContent=a.active_requests.length+' 个请求执行中 · '+duration(Date.now()-oldest);}}}
function renderAgents(agents){for(const a of agents){let ui=agentNodes.get(a.role);if(!ui){const card=element('article','','agent'),top=element('div','','agent-top'),icon=element('div',roleInitials[a.role],'agent-icon'),status=badge('',a.status),name=element('h3',a.name),desc=element('p',roleDescriptions[a.role],'role-desc'),stage=element('p','','agent-stage'),footer=element('div','','agent-footer'),calls=element('span'),tokens=element('span');top.append(icon,status);footer.append(calls,tokens);card.append(top,name,desc,stage,footer);$('#agents').append(card);const percent=element('strong','—','agent-percent'),track=element('div','','progress-track'),fill=element('i'),basis=element('p','','progress-unit');track.append(fill);card.insertBefore(percent,stage);card.insertBefore(track,stage);card.insertBefore(basis,stage);const telemetry=element('p','','agent-telemetry');card.insertBefore(telemetry,footer);ui={card,status,stage,calls,tokens,percent,fill,basis,telemetry};agentNodes.set(a.role,ui);}ui.card.className='agent '+a.status;ui.status.textContent=labels[a.status];ui.status.className='badge '+a.status;ui.stage.textContent=a.last_request?a.last_request.stage:'等待任务依赖';ui.stage.title=a.last_request?.stage||'';ui.calls.textContent=a.requests+' 次请求 · '+a.effort;ui.tokens.textContent=short(a.tokens)+' tokens';const p=snapshot.progress?.agents[a.role];ui.percent.textContent=p?p.percent+'%':'—';ui.fill.style.width=(p?.percent||0)+'%';ui.fill.parentElement.setAttribute('role','progressbar');ui.fill.parentElement.setAttribute('aria-valuenow',String(p?.percent||0));ui.fill.parentElement.setAttribute('aria-valuemin','0');ui.fill.parentElement.setAttribute('aria-valuemax','100');ui.fill.parentElement.setAttribute('aria-label',a.name+'任务进度');ui.basis.textContent=p?p.label+' · '+p.completed+'/'+(p.total||'待定')+' 项'+(p.additional?.length?' · 科学 '+p.additional[0].percent+'% / 双语 '+p.additional[1].percent+'%':''):'此项目尚无可量化计划';ui.basis.title=p?.basis||'';const stats=snapshot.telemetry?.by_role?.[a.role];ui.telemetry.textContent=stats?'输入 '+short(stats.input_tokens)+' / 输出 '+short(stats.output_tokens)+' · 回报 '+stats.output_tokens_per_second.toFixed(1)+' t/s · 工具 '+stats.tools_60s+'/min · 失败 '+stats.failed_requests:'尚无请求用量';}}
function renderStages(stages){const key=JSON.stringify(stages);if(key===stageKey)return;stageKey=key;$('#stage-count').textContent=stages.length+' 个已保存阶段';$('#stages').replaceChildren(...stages.map(s=>{const row=element('div','','stage'),link=element('button','查看','text-button');link.onclick=()=>void openOutput(s.ref,s.name);row.append(element('span','','stage-dot'),element('span',s.name,'stage-name'),badge(labels[s.status]||s.status,s.status),link);return row;}));if(!stages.length)$('#stages').append(element('p','尚无已保存阶段。','muted'));}
async function fetchEvents(){if(eventBusy||!project)return;eventBusy=true;const tag=generation;try{for(let i=0;i<4;i++){const page=await api('/reviewforge/api/monitor-events',cursor===undefined?{}:{cursor});if(tag!==generation)return;if(page.reset)events=[];cursor=page.cursor;const ids=new Set(events.map(e=>e.event_id));events.push(...page.events.filter(e=>!ids.has(e.event_id)));events=events.slice(-1000);if(page.skipped_bytes||page.reset)$('#event-scope').textContent='从日志末尾加载；本次保留最近 1000 条，可导出当前记录';if(page.malformed)message('部分事件行无法解析，其他日志继续显示。');if(!page.has_more||!page.events.length)break;}if(tag===generation){$('#event-count').textContent=number(events.length);if(!frozen){renderRecent();if(view==='events')renderEvents();}}}catch(error){if(tag===generation)errorMessage(error);}finally{if(tag===generation)eventBusy=false;}}
function renderRecent(){const list=events.slice(-7).reverse();$('#recent-events').replaceChildren(...list.map(e=>{const row=element('div','','recent-event'),text=element('div',eventName(e)),stage=element('small',e.stage||e.details?.role||labels[e.execution_kind]);text.append(stage);row.append(element('time',time(e.timestamp)),text);row.tabIndex=0;row.onclick=()=>detail(eventName(e),jsonView(e));row.onkeydown=k=>{if(k.key==='Enter')row.click();};return row;}));if(!list.length)$('#recent-events').append(element('p','等待事件。','muted'));}
function filteredEvents(){const search=$('#event-search').value.toLowerCase(),kind=$('#event-kind').value;return(frozen||events).filter(e=>(kind==='all'||e.execution_kind===kind)&&(!search||JSON.stringify(e).toLowerCase().includes(search)||eventName(e).includes(search)));}
function renderEvents(){const list=filteredEvents().slice().reverse();$('#event-rows').replaceChildren(...list.map(e=>{const row=element('tr'),a=element('td',time(e.timestamp)),b=element('td',eventName(e)),c=element('td',e.stage||'—'),d=element('td'),more=element('td'),button=element('button','展开','text-button');b.append(element('small',e.type));c.append(element('small',e.details?.role||''));d.append(badge(labels[e.execution_kind]||e.execution_kind,e.execution_kind));button.onclick=()=>detail(eventName(e),jsonView(e));more.append(button);row.append(a,b,c,d,more);return row;}));if(!list.length){const row=element('tr'),cell=element('td','没有匹配事件。');cell.colSpan=5;row.append(cell);$('#event-rows').append(row);}}
async function fetchCitations(force=false){if(citationBusy||!project)return;const key=JSON.stringify(snapshot?.citations)+snapshot?.draft?.ref;if(!force&&key===lastCitationsKey)return;citationBusy=true;const tag=generation;try{const result=await api('/reviewforge/api/monitor-citations');if(tag!==generation)return;citations=result;lastCitationsKey=key;renderCitations();}catch(error){if(tag===generation)errorMessage(error);}finally{if(tag===generation)citationBusy=false;}}
function renderCitations(){if(!citations)return;$('#citation-scope').textContent=(citations.version||'尚无稿件')+' · '+citations.checked+'/'+citations.total+' 已保存核查'+(citations.stale_reports?' · '+citations.stale_reports+' 份旧版本结果未计入':'');$('#citation-summary').replaceChildren(...Object.entries(citations.counts).map(([status,count])=>{const e=element('div',labels[status]||status,'citation-chip');e.append(element('b',number(count)));return e;}));const search=$('#citation-search').value.toLowerCase(),filter=$('#citation-filter').value,list=citations.checks.filter(c=>(filter==='all'||c.status===filter)&&(!search||JSON.stringify(c).toLowerCase().includes(search)));$('#citation-rows').replaceChildren(...list.map(c=>{const row=element('tr'),where=element('td',c.source_id),statement=element('td'),status=element('td'),more=element('td'),button=element('button','查看','text-button');where.append(element('small',c.paragraph_id||c.section));statement.append(element('div',c.statement,'statement'));status.append(badge(labels[c.status]||c.status,c.status));if(c.execution_kind)status.append(element('small',labels[c.execution_kind]||c.execution_kind));button.onclick=()=>citationDetail(c);more.append(button);row.append(where,statement,status,more);return row;}));if(!list.length){const row=element('tr'),cell=element('td','没有匹配的引用位置。');cell.colSpan=4;row.append(cell);$('#citation-rows').append(row);}}
function citationDetail(c){const container=element('div');container.append(badge(labels[c.status]||c.status,c.status),element('h3',c.source_id+' · '+(c.paragraph_id||c.section)),element('p',c.statement));if(c.explanation)container.append(element('h3','判断依据'),element('p',c.explanation));if(c.boundary)container.append(element('h3','证据边界'),element('p',c.boundary));for(const q of c.source_quotes||[])container.append(element('blockquote',q.quote),element('small','原文偏移 '+q.start));const sourceButton=element('button','查看来源文本');sourceButton.onclick=async()=>{const tag=generation;try{const source=await api('/reviewforge/api/monitor-source',{source:c.source_id,start:c.source_quotes?.[0]?.start||0});if(tag!==generation)return;const body=element('div');body.append(element('h3',source.title),badge(source.access,'idle'),element('p','字符偏移 '+source.start+' / '+source.total_chars),element('pre',source.text));detail('来源文本',body);}catch(error){errorMessage(error);}};container.append(sourceButton);detail('引文核查详情',container);}
function renderOutputs(items){const key=JSON.stringify(items);if(key===outputsKey)return;outputsKey=key;$('#outputs').replaceChildren(...items.map(item=>{const b=element('button',item.label,'output-item'+(item.ref===outputRef?' selected':''));b.dataset.ref=item.ref;b.append(element('small',item.kind+' · '+item.ref.split('/').at(-1)));b.onclick=()=>void openOutput(item.ref,item.label);return b;}));if(!items.length)$('#outputs').append(element('p','尚无产物。','muted'));}
async function openOutput(ref,label){const tag=generation;try{const data=await api('/reviewforge/api/monitor-artifact',{ref});if(tag!==generation)return;output=data;outputRef=ref;setView('outputs');$('#output-title').textContent=label;$('#export-output').disabled=false;$('#output-preview').replaceChildren(reportView(data));document.querySelectorAll('.output-item').forEach(b=>b.classList.toggle('selected',b.dataset.ref===ref));}catch(error){if(tag===generation)errorMessage(error);}}
function reportView(data){const root=element('div');if(data.title)root.append(element('h3',data.title));if(data.version)root.append(badge(data.version,'idle'));if(data.origin)root.append(badge(labels[data.origin]||data.origin,data.origin));for(const key of ['summary','reason','abstract','body','synopsis'])if(data[key])root.append(element('h3',({summary:'概述',reason:'理由',abstract:'摘要',body:'正文',synopsis:'梗概'})[key]),element('p',String(data[key])));for(const key of ['findings','responses','adjudications','checks','rows'])if(Array.isArray(data[key])){root.append(element('h3',({findings:'审稿问题',responses:'作者回应',adjudications:'编辑裁决',checks:'核查记录',rows:'矩阵'})[key]));for(const row of data[key]){const box=element('details'),title=element('summary',[row.finding_id||row.occurrence_id||row.dimension||'',row.severity||row.status||row.decision||''].filter(Boolean).join(' · '));box.append(title);if(row.locator?.quote)box.append(element('blockquote',row.locator.quote));for(const field of ['explanation','reason','impact','requirement','close_when','basis','before','after','boundary'])if(row[field])box.append(element('h3',field),element('p',String(row[field])));box.append(jsonView(row));root.append(box);}}for(const key of ['gaps','remaining_gaps','remaining_uncertainty','coverage'])if(data[key]?.length)root.append(element('h3',key),element('p',Array.isArray(data[key])?data[key].join('\n'):data[key]));const raw=element('details');raw.append(element('summary','完整 JSON'),jsonView(data));root.append(raw);return root;}
// Circuit nodes light up only for recorded in-flight requests with a live PID.
function renderFlow(agents){renderNetwork(agents,snapshot);}
document.querySelectorAll('button.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#all-events').onclick=()=>setView('events');$('#project').onchange=()=>selectProject($('#project').value);$('#refresh').onclick=async()=>{try{await loadProjects();if(project){snapshot=await api('/reviewforge/api/monitor');renderSnapshot();await fetchEvents();if(view==='citations')await fetchCitations(true);}}catch(error){errorMessage(error);}};$('#freeze-events').onclick=()=>{frozen=frozen?null:events.slice();$('#freeze-events').textContent=frozen?'继续更新':'冻结列表';renderEvents();if(!frozen)renderRecent();};$('#event-search').oninput=renderEvents;$('#event-kind').onchange=renderEvents;$('#citation-search').oninput=renderCitations;$('#citation-filter').onchange=renderCitations;$('#export-events').onclick=()=>download(project+'-events.json',filteredEvents());$('#export-citations').onclick=()=>{if(citations)download(project+'-citations.json',citations);};$('#export-output').onclick=()=>{if(output)download(project+'-'+outputRef.split('/').at(-1),output);};$('#detail-close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail')&&e.offsetX<0)$('#detail').close();};window.addEventListener('beforeunload',()=>stream?.close());setInterval(renderActivity,1000);setInterval(()=>void loadProjects().catch(errorMessage),15000);void loadProjects().catch(errorMessage);

function renderProgress(progress){const panel=$('#workflow-progress');panel.hidden=!progress;if(!progress)return;$('#overall-percent').textContent=progress.percent+'%';$('#overall-fill').style.width=progress.percent+'%';$('#progress-basis').textContent=progress.basis+' '+progress.request_note;$('#progress-scope').textContent=progress.scope;$('#progress-phases').replaceChildren(...progress.phases.map(p=>{const row=element('div','','progress-phase'+(snapshot.agents.some(a=>a.role===p.role&&a.status==='running')?' active':'')),heading=element('div'),label=element('span',p.label),percent=element('b',p.percent+'%'),track=element('div','','progress-track'),fill=element('i'),count=element('small',p.completed+'/'+(p.total||'待定')+' 项');heading.append(label,percent);fill.style.width=p.percent+'%';track.append(fill);row.title=p.basis;row.append(heading,track,count);return row;}));}

let rateSamples=[],rateProject='';
function renderTelemetry(t){if(!t)return;if(rateProject!==project){rateSamples=[];rateProject=project;}rateSamples.push(t.output_tokens_per_second);rateSamples=rateSamples.slice(-90);const max=Math.max(1,...rateSamples);$('#rate-line').setAttribute('points',rateSamples.map((n,i)=>(i*600/Math.max(1,rateSamples.length-1)).toFixed(1)+','+(68-n/max*60).toFixed(1)).join(' '));const fmt=n=>n===null?'—':Number(n).toFixed(1);const rows=[['活动 Agent',t.active_agents+' / 8'],['并发请求',t.active_requests],['输出回报速率',fmt(t.output_tokens_per_second)+' t/s'],['输入回报速率',fmt(t.input_tokens_per_second)+' t/s'],['60 秒工具调用',t.tools_60s],['60 秒请求回报',t.completed_requests_60s],['累计输入 tokens',short(t.input_tokens)],['累计输出 tokens',short(t.output_tokens)],['预算占用（含预留）',t.budget_percent===null?'无限额':fmt(t.budget_percent)+'%'],['60 秒请求均耗时',fmt(t.mean_request_seconds_60s)+' s'],['请求输出均速（含等待）',fmt(t.request_wall_output_tps_60s)+' t/s'],['失败请求 / 未确认',t.failed_requests+' / '+t.unconfirmed_requests]];$('#telemetry-metrics').replaceChildren(...rows.map(([label,value])=>{const e=element('div','','telemetry-metric');e.append(element('small',label),element('b',String(value)));return e;}));$('#telemetry-window').textContent='60 秒观察窗'+(t.window_complete?'':' · 当前日志覆盖不足，速率为下界');$('#telemetry-note').textContent=t.note;$('#live-interactions').replaceChildren(...t.latest_tools.slice(0,5).map(x=>{const row=element('div','','interaction');row.append(element('time',time(x.at)),element('span',(roleInitials[x.role]||x.role)+' → '+x.tool+(x.source_id?' · '+x.source_id:'')));row.title=x.stage;return row;}));if(!t.latest_tools.length)$('#live-interactions').append(element('p','观察窗口内暂无工具交互','muted'));}

function publicProjectLabel(id){return id.startsWith('aidd-')?'AIDD 分析':id.startsWith('alpha-')?'α 核素炎症综述':id;}
let comparisonBusy=false;
async function loadComparison(){if(comparisonBusy)return;comparisonBusy=true;try{const list=await api('/reviewforge/api/monitor-projects');const cards=await Promise.all(list.map(async item=>{try{const url=new URL('/reviewforge/api/monitor',RF_SERVER);url.searchParams.set('project',item.id);const response=await cloudFetch(url);if(!response.ok)throw Error('Unavailable');return comparisonCard(await response.json());}catch{const card=element('div','','parallel-project stale');card.append(element('h3',publicProjectLabel(item.id)),element('p','暂时无法读取该任务','muted'));return card;}}));$('#parallel-projects').replaceChildren(...cards);}catch{$('#parallel-projects').replaceChildren(element('p','任务列表连接中断，正在重试。','muted'));}finally{comparisonBusy=false;}}
function comparisonCard(s){const p=s.progress?.percent||0,running=s.runtime.state==='running'&&!s.cloud?.stale,card=element('button','','parallel-project'+(running?' running':'')+(s.cloud?.stale?' stale':''));card.type='button';card.setAttribute('aria-label',publicProjectLabel(s.project.id)+'，进度'+p+'%，点击查看详情');card.setAttribute('aria-pressed',String(s.project.id===project));card.dataset.projectId=s.project.id;const top=element('div','','parallel-top'),name=element('h3',publicProjectLabel(s.project.id)),status=element('span',s.cloud?.stale?'同步过期':running?'执行中':s.project.status==='collecting'?'证据准备':s.project.status==='cancelled'?'尚未启动':labels[s.runtime.state]||s.runtime.state,'parallel-status');top.append(name,status);const progress=element('div','','parallel-progress');progress.append(element('strong',p+'%'),element('span','已保存流程进度'));const track=element('div','','parallel-track'),fill=element('i');fill.style.width=p+'%';track.append(fill);const metrics=element('div','','parallel-metrics');for(const [label,value]of [['活动 Agent',(s.telemetry?.active_agents||0)+'/8'],['并发请求',s.telemetry?.active_requests||0],['实测 Token',short(s.measured_tokens)]]){const metric=element('div');metric.append(element('small',label),element('b',String(value)));metrics.append(metric);}const active=s.active_requests?.[0];const note=s.cloud?.stale?'本机同步已超过20秒未更新':active?(roleDescriptions[active.role]||active.role):p===0?(s.project.status==='collecting'?'正在准备证据；原生流程尚无已保存检查点':'尚无原生检查点；准备资料不计入流程百分比'):'当前没有执行中的模型请求';card.append(top,progress,track,metrics,element('p',note,'parallel-note'));card.onclick=()=>{selectProject(s.project.id);setView('overview');document.querySelectorAll('.parallel-project').forEach(c=>c.setAttribute('aria-pressed',String(c.dataset.projectId===s.project.id)));};return card;}
setInterval(()=>void loadComparison(),5000);void loadComparison();
