const RF_SERVER='https://122.51.44.155';
let rfToken=sessionStorage.getItem('rf_monitor_session')||'';
let resolveAuth;
const RF_AUTH_READY=new Promise(resolve=>{resolveAuth=resolve;});
function lockMonitor(){document.body.classList.add('auth-locked');let panel=document.getElementById('rf-login');if(!panel){panel=document.createElement('section');panel.id='rf-login';panel.className='rf-login';panel.innerHTML=`<form><div class="eyebrow">REVIEW FORGE / SECURE ACCESS</div><h1>综述运行监控</h1><p>输入访问口令，查看你有权限的综述任务。</p><label for="rf-password">访问口令</label><input id="rf-password" type="password" autocomplete="current-password" required maxlength="200"><button type="submit">进入监控</button><p id="rf-login-error" role="alert"></p><small>科研文稿与原始证据保留在本机</small></form>`;document.body.append(panel);panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=panel.querySelector('input'),button=panel.querySelector('button'),error=panel.querySelector('#rf-login-error');button.disabled=true;error.textContent='正在验证…';try{const response=await fetch(new URL('/reviewforge/login',RF_SERVER),{method:'POST',credentials:'omit',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password:input.value})});input.value='';const result=await response.json();if(!response.ok)throw Error(result.error||'验证失败');rfToken=result.token;sessionStorage.setItem('rf_monitor_session',rfToken);unlockMonitor();}catch(err){error.textContent=err.message||'连接失败，请重试';}finally{button.disabled=false;}};}panel.hidden=false;}
function unlockMonitor(){document.body.classList.remove('auth-locked');const panel=document.getElementById('rf-login');if(panel)panel.hidden=true;resolveAuth();if(!document.getElementById('rf-logout')){const button=document.createElement('button');button.id='rf-logout';button.textContent='退出';button.onclick=async()=>{try{await fetch(new URL('/reviewforge/logout',RF_SERVER),{method:'POST',credentials:'omit',headers:{Authorization:'Bearer '+rfToken}});}finally{sessionStorage.removeItem('rf_monitor_session');location.reload();}};document.querySelector('.connection').append(button);}}
async function cloudFetch(url,options={}){await RF_AUTH_READY;const response=await fetch(url,{...options,credentials:'omit',headers:{...options.headers,Authorization:'Bearer '+rfToken}});if(response.status===401){sessionStorage.removeItem('rf_monitor_session');rfToken='';lockMonitor();throw Error('会话已过期，请重新输入口令');}return response;}
if(rfToken){fetch(new URL('/reviewforge/api/monitor-projects',RF_SERVER),{credentials:'omit',headers:{Authorization:'Bearer '+rfToken}}).then(response=>{if(response.ok)unlockMonitor();else{sessionStorage.removeItem('rf_monitor_session');rfToken='';lockMonitor();}}).catch(()=>lockMonitor());}else lockMonitor();
class PhoneStream{constructor(url){this.url=new URL(url,RF_SERVER);this.url.pathname=this.url.pathname.replace('/monitor-stream','/monitor');this.listeners=new Map();this.closed=false;queueMicrotask(()=>this.poll());}addEventListener(name,fn){this.listeners.set(name,fn);}close(){this.closed=true;clearTimeout(this.timer);}async poll(){if(this.closed)return;try{const response=await cloudFetch(this.url);if(!response.ok)throw Error('Monitor unavailable');const snapshot=await response.json();if(!this.closed)this.listeners.get('snapshot')?.({data:JSON.stringify(snapshot)});}catch{if(!this.closed)this.onerror?.();}finally{if(!this.closed)this.timer=setTimeout(()=>this.poll(),2500);}}}
